name: "Production - Web Deploy"

on:
  push:
    branches: [ production ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'deploy/app/web/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.template.yml
    secrets: inherit
    with:
      service_name: "web"
      environment: "production"
      docker_file_path: "apps/web/Dockerfile"
      helm_chart_dir: "deploy/app/web"

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.template.yml
    secrets: inherit
    with:
      service_name: "web"
      environment: "production"
      helm_chart_dir: "deploy/app/web"
      node_group_id: ${{ vars.YC_NODE_GROUP_ID }}
      image_tag: ${{ needs.build.outputs.image_tag }}
